"""initial schema

Revision ID: 46dba3be7663
Revises: 
Create Date: 2026-05-24 19:24:43.315003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46dba3be7663'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('spoiler_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('basho',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rikishi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('debut_date', sa.Date(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basho_rikishi',
    sa.Column('basho_id', sa.String(), nullable=False),
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Text(), nullable=True),
    sa.Column('rank_value', sa.Integer(), nullable=True),
    sa.Column('division', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['basho_id'], ['basho.id'], ),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.PrimaryKeyConstraint('basho_id', 'rikishi_id')
    )
    op.create_table('match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('basho_id', sa.String(), nullable=False),
    sa.Column('rikishi1_id', sa.Integer(), nullable=False),
    sa.Column('rikishi2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('kimarite', sa.Text(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('division', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['basho_id'], ['basho.id'], ),
    sa.ForeignKeyConstraint(['rikishi1_id'], ['rikishi.id'], ),
    sa.ForeignKeyConstraint(['rikishi2_id'], ['rikishi.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['rikishi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_basho_day', 'match', ['basho_id', 'day'], unique=False)
    op.create_index('idx_match_basho_division_day', 'match', ['basho_id', 'division', 'day'], unique=False)
    op.create_table('measurement',
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('basho_id', sa.String(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basho_id'], ['basho.id'], ),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.PrimaryKeyConstraint('rikishi_id', 'basho_id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('basho_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('budget_pence', sa.Integer(), nullable=False),
    sa.Column('roster_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basho_id'], ['basho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_one_live_tournament', 'tournament', ['status'], unique=True, postgresql_where=sa.text("status IN ('setup', 'drafting', 'active')"), sqlite_where=sa.text("status IN ('setup', 'drafting', 'active')"))
    op.create_table('rikishi_price',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'rikishi_id')
    )
    op.create_table('roster_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('participant_user_id', sa.Uuid(), nullable=False),
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('purchase_price_pence', sa.Integer(), nullable=False),
    sa.Column('acquired_via', sa.String(length=16), nullable=False),
    sa.Column('acquired_before_day', sa.Integer(), nullable=False),
    sa.Column('sale_price_pence', sa.Integer(), nullable=True),
    sa.Column('released_before_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roster_active', 'roster_entry', ['tournament_id', 'participant_user_id'], unique=False, postgresql_where=sa.text('released_before_day IS NULL'), sqlite_where=sa.text('released_before_day IS NULL'))
    op.create_table('score_adjustment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('participant_user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_award',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'rikishi_id', 'kind')
    )
    op.create_table('tournament_participant',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('draft_seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'user_id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('participant_user_id', sa.Uuid(), nullable=False),
    sa.Column('sold_entry_id', sa.Uuid(), nullable=False),
    sa.Column('bought_entry_id', sa.Uuid(), nullable=False),
    sa.Column('effective_before_day', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bought_entry_id'], ['roster_entry.id'], ),
    sa.ForeignKeyConstraint(['participant_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sold_entry_id'], ['roster_entry.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    op.drop_table('tournament_participant')
    op.drop_table('tournament_award')
    op.drop_table('score_adjustment')
    op.drop_index('idx_roster_active', table_name='roster_entry', postgresql_where=sa.text('released_before_day IS NULL'), sqlite_where=sa.text('released_before_day IS NULL'))
    op.drop_table('roster_entry')
    op.drop_table('rikishi_price')
    op.drop_index('idx_one_live_tournament', table_name='tournament', postgresql_where=sa.text("status IN ('setup', 'drafting', 'active')"), sqlite_where=sa.text("status IN ('setup', 'drafting', 'active')"))
    op.drop_table('tournament')
    op.drop_table('measurement')
    op.drop_index('idx_match_basho_division_day', table_name='match')
    op.drop_index('idx_match_basho_day', table_name='match')
    op.drop_table('match')
    op.drop_table('basho_rikishi')
    op.drop_table('rikishi')
    op.drop_table('basho')
    op.drop_table('app_user')
    # ### end Alembic commands ###
